### ISSUE TITLE
Upgrade from PHP 7.0 to PHP 7.2 fails

### ISSUE THREAD

**Issue by pixelbrackets** [helhum/dotenv-connector#11]
Hi, I experienced the following behaviour while upgrade a project to a new PHP version.

From:
* PHP 7.0.30
* helhum/dotenv-connector 2.1.0
  * depends on symfony/dotenv 3.4.14

To:
* PHP 7.2.7
* helhum/dotenv-connector 2.1.0
  * depends on symfony/dotenv 4.1.3

Composer Update fails with the following error message

```php
PHP Fatal error:  Uncaught TypeError: Return value of Symfony\Component\Dotenv\Dotenv::populate() must be an instance of Symfony\Component\Dotenv\void, none returned in /home/path-to-project/www/vendor/symfony/dotenv/Dotenv.php:95
Stack trace:
#0 /home/path-to-project/www/vendor/symfony/dotenv/Dotenv.php(57): Symfony\Component\Dotenv\Dotenv->populate(Array)
#1 /home/path-to-project/www/vendor/helhum/dotenv-include.php(4): Symfony\Component\Dotenv\Dotenv->load('/home/path-to-p...')
#2 /home/path-to-project/www/vendor/helhum/dotenv-include.php(6): Helhum\DotEnvConnector\IncludeFile->{closure}('/home/path-to-p...')
#3 /home/path-to-project/www/vendor/helhum/dotenv-connector/src/IncludeFile.php(60): require('/home/path-to-p...')
#4 /home/path-to-project/www/vendor/helhum/dotenv-connector/src/Plugin.php(78): Helhum\DotEnvConnector\IncludeFile->dump()
#5 [internal function]: Helhum\DotEnvConnector\Plugin->onPreAutoloadDump(Object(Composer\Script\Event))
#6 phar:///usr/local/bin/compose in /home/path-to-project/www/vendor/symfony/dotenv/Dotenv.php on line 95

Fatal error: Uncaught TypeError: Return value of Symfony\Component\Dotenv\Dotenv::populate() must be an instance of Symfony\Component\Dotenv\void, none returned in /home/path-to-project/www/vendor/symfony/dotenv/Dotenv.php:95
Stack trace:
#0 /home/path-to-project/www/vendor/symfony/dotenv/Dotenv.php(57): Symfony\Component\Dotenv\Dotenv->populate(Array)
#1 /home/path-to-project/www/vendor/helhum/dotenv-include.php(4): Symfony\Component\Dotenv\Dotenv->load('/home/path-to-p...')
#2 /home/path-to-project/www/vendor/helhum/dotenv-include.php(6): Helhum\DotEnvConnector\IncludeFile->{closure}('/home/path-to-p...')
#3 /home/path-to-project/www/vendor/helhum/dotenv-connector/src/IncludeFile.php(60): require('/home/path-to-p...')
#4 /home/path-to-project/www/vendor/helhum/dotenv-connector/src/Plugin.php(78): Helhum\DotEnvConnector\IncludeFile->dump()
#5 [internal function]: Helhum\DotEnvConnector\Plugin->onPreAutoloadDump(Object(Composer\Script\Event))
#6 phar:///usr/local/bin/compose in /home/path-to-project/www/vendor/symfony/dotenv/Dotenv.php on line 95
```

Looks like a wrong argument pass?

**Comment by pixelbrackets** [comment]
Sorry, nevermind. See https://github.com/symfony/symfony/issues/25469 → The error does not happen on the machine with PHP 7.2 installed, but on machines with PHP 7.0 requiring packages for PHP 7.2 via Composer (by setting the platform param). Solved. 🤭
