### ISSUE TITLE
Upgrade to 2.1.0 causes class not found error

### ISSUE THREAD

**Issue by markuspoerschke** [helhum/dotenv-connector#9]
When upgrading to `2.1.0` then a class not found error is raised. The solution for us was to downgrade to `2.0.0` again.

Here you can find the complete output:

```
➜  website git:(develop) ✗ composer up 
Gathering patches for root package.
Loading composer repositories with package information                                                                                                 Updating dependencies (including require-dev)         Package operations: 0 installs, 7 updates, 3 removals
  - Removing twig/twig (v2.4.8)
  - Removing XXXXXXX/XXXXXXX (1.0.0)
  - Removing XXXXXXX/XXXXXXX (dev-master)
Gathering patches for root package.
Gathering patches for dependencies. This might take a minute.
  - Updating cweagans/composer-patches (1.6.4 => 1.6.5): Loading from cache
  - Updating helhum/dotenv-connector (v2.0.3 => v2.1.0): Loading from cache
  - Updating typo3fluid/fluid (2.5.3 => 2.5.4):  Checking out bcd0ff44dd
  - Updating helhum/typo3-console (5.3.0 => 5.3.2):  Checking out b53d349ee0
  - Updating gridelementsteam/gridelements (8.2.1 => 8.2.3):  Checking out fc617c5e23
  - Updating typo3-ter/html-minifier (1.1.5 => 1.1.6): Loading from cache
  - Updating mask/mask (3.1.0 => v3.3.1): Loading from cache
Package typo3-ter/skip-page-is-being-generated is abandoned, you should avoid using it. Use qbus/skip-page-is-being-generated instead.
Writing lock file
Generating autoload files
PHP Fatal error:  Uncaught Error: Class 'Symfony\Component\Dotenv\Dotenv' not found in /var/www/vendor/helhum/dotenv-include.php:4
Stack trace:
#0 /var/www/vendor/helhum/dotenv-include.php(6): Helhum\DotEnvConnector\IncludeFile->{closure}('/Users/poerschk...')
#1 /var/www/vendor/helhum/dotenv-connector/src/IncludeFile.php(60): require('/Users/poerschk...')
#2 /var/www/vendor/helhum/dotenv-connector/src/Plugin.php(79): Helhum\DotEnvConnector\IncludeFile->dump()
#3 [internal function]: Helhum\DotEnvConnector\Plugin->onPreAutoloadDump(Object(Composer\Script\Event))
#4 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(176): call_user_func(Array, Object(Composer\Script\Event))
#5 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(96): Composer\EventDispatcher\EventDispatcher->doDispatch(Object(Composer\Script\Event))
#6  in /var/www/vendor/helhum/dotenv-include.php on line 4

Fatal error: Uncaught Error: Class 'Symfony\Component\Dotenv\Dotenv' not found in /var/www/vendor/helhum/dotenv-include.php:4
Stack trace:
#0 /var/www/vendor/helhum/dotenv-include.php(6): Helhum\DotEnvConnector\IncludeFile->{closure}('/Users/poerschk...')
#1 /var/www/vendor/helhum/dotenv-connector/src/IncludeFile.php(60): require('/Users/poerschk...')
#2 /var/www/vendor/helhum/dotenv-connector/src/Plugin.php(79): Helhum\DotEnvConnector\IncludeFile->dump()
#3 [internal function]: Helhum\DotEnvConnector\Plugin->onPreAutoloadDump(Object(Composer\Script\Event))
#4 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(176): call_user_func(Array, Object(Composer\Script\Event))
#5 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(96): Composer\EventDispatcher\EventDispatcher->doDispatch(Object(Composer\Script\Event))
#6  in /var/www/vendor/helhum/dotenv-include.php on line 4
```

In my opinion the problem is related to 056776aaede09afdc05b85d0c86749484ac21957.

**Comment by helhum** [comment]
good point. will fix it asap

**Comment by helhum** [comment]
@kaisercanvas I guess you were affected by this bug as well. Working on a fix now

**Comment by helhum** [comment]
@markuspoerschke @kaisercanvas can you confirm the fix indeed works for you?

You can test by temporarily requiring dev-master of this package.

If you confirm the fix works, I will release a 2.1.1

**Comment by markuspoerschke** [comment]
Now I get a new error message:

```
➜  website git:(develop) composer up helhum/dotenv-connector
Loading composer repositories with package information                                                                                               Updating dependencies (including require-dev)         Package operations: 0 installs, 1 update, 0 removals
  - Removing helhum/dotenv-connector (v2.0.3)
  - Installing helhum/dotenv-connector (dev-master 9f4c58d): Cloning 9f4c58dc02 from cache
Writing lock file
Generating autoload files
PHP Fatal error:  Uncaught TypeError: Argument 2 passed to Helhum\DotEnvConnector\IncludeFile::__construct() must be an instance of Composer\Autoload\ClassLoader, string given, called in /var/www/vendor/helhum/dotenv-connector/src/Plugin.php on line 78 and defined in /var/www/vendor/helhum/dotenv-connector/src/IncludeFile.php:46
Stack trace:
#0 /var/www/vendor/helhum/dotenv-connector/src/Plugin.php(78): Helhum\DotEnvConnector\IncludeFile->__construct(Object(Helhum\DotEnvConnector\Config), '/var/www...')
#1 [internal function]: Helhum\DotEnvConnector\Plugin->onPreAutoloadDump(Object(Composer\Script\Event))
#2 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(176): call_user_func(Array, Object(Composer\Script\Event))
#3 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(96): Composer\EventDispatcher\EventDispatcher->doDispatc in /var/www/vendor/helhum/dotenv-connector/src/IncludeFile.php on line 46

Fatal error: Uncaught TypeError: Argument 2 passed to Helhum\DotEnvConnector\IncludeFile::__construct() must be an instance of Composer\Autoload\ClassLoader, string given, called in /var/www/vendor/helhum/dotenv-connector/src/Plugin.php on line 78 and defined in /var/www/vendor/helhum/dotenv-connector/src/IncludeFile.php:46
Stack trace:
#0 /var/www/vendor/helhum/dotenv-connector/src/Plugin.php(78): Helhum\DotEnvConnector\IncludeFile->__construct(Object(Helhum\DotEnvConnector\Config), '/var/www...')
#1 [internal function]: Helhum\DotEnvConnector\Plugin->onPreAutoloadDump(Object(Composer\Script\Event))
#2 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(176): call_user_func(Array, Object(Composer\Script\Event))
#3 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(96): Composer\EventDispatcher\EventDispatcher->doDispatc in /var/www/vendor/helhum/dotenv-connector/src/IncludeFile.php on line 46
```

**Comment by helhum** [comment]
@markuspoerschke Please run `composer require helhum/dotenv-connector dev-master --no-plugins && composer du`

**Comment by helhum** [comment]
@markuspoerschke since I cannot reproduce your initial error, can you tell me which composer version you were using when seeing the error?

**Comment by helhum** [comment]
Hm, as far as I can see from composer code, this should never happen. So I would be interested in an exact setup to reproduce it. Can you provide a root composer.json with lock, alongside a composer version and the command to reproduce the error?

**Comment by markuspoerschke** [comment]
@helhum You are right. The first time, an exception is thrown. Running `composer up` or `composer install` a second time works without errors.

So it works 👍

**Comment by helhum** [comment]
@markuspoerschke hm, okay. I wasn't even able to reproduce it when calling it the first time. For me it always works. So I would still be interested in how to reproduce it in general.
